import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";
import { createClient } from "@/utils/supabase/server";
import { ReactNode } from "react";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JLL Fresh Produce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // Construct the Google Maps script URL with your API key
  const googleMapsUrl = `https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`;

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider serverSession={session}>{children}</AuthProvider>
        {/* Load the Google Maps script globally with async and defer */}
        <Script src={googleMapsUrl} async defer />
      </body>
    </html>
  );
}
